### ISSUE TITLE
Server error 5006 when using Sage Pay Server

### ISSUE THREAD

**Issue by Stocker6** [academe/OmniPay-SagePay-Demo#1]
Hi,
I've uploaded this demo and set everything up (I think!) on my server, Sage pay test server has my server IP as valid, but when I try the demo the transaction fails with the following error - Server error 5006: Unable to redirect to Vendor's web site. The Vendor failed to provide a RedirectionURL.

Everything looks fine, I get redirected to the test checkout page at testcheckout.sagepay.com, enter so test card details, then submit the payment and it processes for well over 30 seconds before giving the dreaded error message.

I'm getting this in my own code so I was hoping to get yours working and see where I'm going wrong. Any pointers would be great as I'm getting so frustrated with getting these payments working.

Thanks,
Lee

**Comment by judgej** [comment]
If you are getting a 30 second delay, then the URL you have told Sage Pay to send the results to (the `notificationUrl`) is not responding _at all_. Either the domain is duff, or you have a firewall preventing Sage Pay getting in. Check your HTTP logs to see.

**Comment by judgej** [comment]
If you get this error with no delay, then your notification handler is not returning a message in the right format. This can often happen if there are PHP errors - the return text must be a very clean two or three line result with `\r\n` (possibly t'other way around - but handled by OmniPay regardless) for the line endings, regardless of what the result is (e.g. you accept the data, reject it, or the data is invalid or is not signed correctly).

**Comment by JerseyCo** [comment]
Hi,

I've tested your demo code but but keep getting getting a catch error in the secpay-confirm.php file and so executes the  $responseMessage->invalid($finalUrl, $e->getMessage());.

The catch message is "Invalid response from payment gateway", can you offer any advise.

Many thanks

Mark

**Comment by judgej** [comment]
@JerseyCo Where is this error coming from, and what is in your secpay-confirm.php? If it is Sage Pay you are using, and the error is happening at `$responseMessage = $requestMessage->send();` in the notify handler, then it means the OmniPay driver was not happy with what it received from Sage Pay.

The notification message from Sage Pay will be signed using details in the `transactionReference` saved right at the start. You should confirm that the notification handler is getting the correct `transactionReference` from the database and [passing it to the driver](https://github.com/academe/OmniPay-SagePay-Demo/blob/master/sagepay-confirm.php#L43).

**Comment by JerseyCo** [comment]
Thanks for getting back to me so quickly. Apologies there was a typo in my first post, the file is the sagepay-confirm.php used from your repository.

I've checked and the correct `transactionReference` is being sent but the notify handler from  `$responseMessage = $requestMessage->send();` is still giving the message "Invalid response from payment gateway".

Thanks

**Comment by judgej** [comment]
I'm still not sure where the "Invalid response from payment gateway" message is coming from. It's not a Sage Pay error, so far as I can see, and it's not in the demo scripts or the OmniPay drivers. I am asking just to make sure I fully understand what you have set up.

In your notification handler, before exiting with `$responseMessage->invalid($finalUrl, $e->getMessage());`, can you log `$transactionReference` and `$_POST`? Those two things give us the two parts of the equation that re not matching up: the message actually received from Sage Pay, and the message your site is expecting to get from Sage Pay.

**Comment by JerseyCo** [comment]
I log the "Invalid response from payment gateway" message here:

```
try {
    $responseMessage = $requestMessage->send();
} catch(\Exception $e) {
    //log message
    Storage::update($transactionId."-e", [
        'message' => $e->getMessage(),
    ]); 

    // InvalidResponseException will not catch a null transactionReference.
    // You may want to catch them separately and return different error messages.
    // This is a nasty hack, manually creating a message in the
    // event of an exception caused by a security failure.
    $requestMessage = $gateway->completePurchase([]);
    $responseMessage = new ServerCompleteAuthorizeResponse($requestMessage, []);
    $responseMessage->invalid($finalUrl, $e->getMessage());
}
```

From a quick Google search, it looks like Omnipay might return the invalid message - https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/Exception/InvalidResponseException.php

Here's the `$_POST`log:

`{"message":{"VPSProtocol":"3.00","TxType":"PAYMENT","VendorTxCode":"phpne-demo-96756483","VPSTxId":"{D2239A0A-B1B6-0800-7AC4-F093A6FBE870}","Status":"OK","StatusDetail":"0000 : The Authorisation was Successful.","TxAuthNo":"12279689","AVSCV2":"SECURITY CODE MATCH ONLY","AddressResult":"NOTMATCHED","PostCodeResult":"NOTMATCHED","CV2Result":"MATCHED","GiftAid":"0","3DSecureStatus":"NOTCHECKED","CardType":"VISA","Last4Digits":"0006","VPSSignature":"BC06158FFA2EFBAC729F7C3420D3222B","DeclineCode":"00","ExpiryDate":"1118","BankAuthCode":"999777"}}`

and the `$transactionReference`:

`{"message":"{\"SecurityKey\":\"RC7PPRA6FZ\",\"VPSTxId\":\"{D2239A0A-B1B6-0800-7AC4-F093A6FBE870}\",\"VendorTxCode\":\"phpne-demo-96756483\"}"}`

**Comment by judgej** [comment]
Ah, thanks, I didn't find that error message in my Google searches :-)

Those back-slashes in your transaction reference don't look like they should be there. Are they being double-escaped when initially being stored in the database? Try removing them before passing the `transactionReference` into `$requestMessage`, e.g. `$transactionReference = str_replace('\', '', $transactionReference)`

If that helps, then we can work out how they are getting into there later.

Also is your vendor name being set correctly here in `sagepay-notify.php`:

``` php
$gateway = OmniPay::create('SagePay\Server')
    ->setVendor(getenv('VENDOR')) // <<<<<<<<<<<<
    ->setTestMode(true);
```

The data on the face of it looks okay. If the back-slashes mean the transaction reference cannot be decoded, then that would cause this error. Similarly if the vendor name is not set or not set correctly (it will be all lower-case).

**Comment by JerseyCo** [comment]
I finally got to the bottom of it, I had the Vendor set as uppercase, which it doesn't seem to like - very strange as the initial card authorisation goes through and shows in the Sagepay account. The main thing is it's working now. Thanks very much for your help.

**Comment by judgej** [comment]
Cool :-)

This makes perfect sense. Sage Pay does not care if you send an upper or lower case vendor (it ought to, but it just "helpfully" ignores the case, which is why we are talking about it now). However, when the signature is generated, in the notification message, Sage Pay will always used the lower-case vendor name that it has on record. If we then don't use the same lower-case vendor name when we check the signature is valid, then we get this error.

We can avoid this by making sure we always make the vendor name lower-case before we use it to construct the signature. It will be a tiny change, though I first need to make sure the signature is ALWAYS and without exception, lower case. Thanks for helping out and not giving up!

**Comment by judgej** [comment]
I've raised it as an issue: https://github.com/thephpleague/omnipay-sagepay/issues/73
